"""Tool contracts, their execution runner, and the simulated backends they read."""

from ap_agent.tools.base import ToolCallResult, ToolRunner, ToolSpec, describe_tools
from ap_agent.tools.contracts import (
    ALL_TOOL_SPECS,
    CHECK_INVOICE_HISTORY,
    GET_AUTHORITY_DELEGATION,
    GET_PURCHASE_ORDER,
    GET_VENDOR_RECORD,
    RETRIEVE_DOCUMENTS,
    SIMULATED_POSTING_SYSTEM,
    SUBMIT_FINANCE_DECISION,
    CheckInvoiceHistoryInput,
    CheckInvoiceHistoryOutput,
    GetDelegationInput,
    GetDelegationOutput,
    GetPurchaseOrderInput,
    GetPurchaseOrderOutput,
    GetVendorInput,
    GetVendorOutput,
    RetrieveDocumentsInput,
    RetrieveDocumentsOutput,
    SubmitFinanceDecisionInput,
    check_invoice_history,
    get_authority_delegation,
    get_purchase_order,
    get_vendor_record,
    retrieve_finance_documents,
    submit_finance_decision,
)
from ap_agent.tools.mock_backends import DEFAULT_MOCK_DATA_DIR, KNOWN_PROFILES, MockBackends

__all__ = [
    "ALL_TOOL_SPECS",
    "CHECK_INVOICE_HISTORY",
    "DEFAULT_MOCK_DATA_DIR",
    "GET_AUTHORITY_DELEGATION",
    "GET_PURCHASE_ORDER",
    "GET_VENDOR_RECORD",
    "KNOWN_PROFILES",
    "RETRIEVE_DOCUMENTS",
    "SIMULATED_POSTING_SYSTEM",
    "SUBMIT_FINANCE_DECISION",
    "CheckInvoiceHistoryInput",
    "CheckInvoiceHistoryOutput",
    "GetDelegationInput",
    "GetDelegationOutput",
    "GetPurchaseOrderInput",
    "GetPurchaseOrderOutput",
    "GetVendorInput",
    "GetVendorOutput",
    "MockBackends",
    "RetrieveDocumentsInput",
    "RetrieveDocumentsOutput",
    "SubmitFinanceDecisionInput",
    "ToolCallResult",
    "ToolRunner",
    "ToolSpec",
    "check_invoice_history",
    "describe_tools",
    "get_authority_delegation",
    "get_purchase_order",
    "get_vendor_record",
    "retrieve_finance_documents",
    "submit_finance_decision",
]
